language: python
# List the versions of Python you'd like to test against
python:
  - 3.6
  - 3.7
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
# List the versions of Django you'd like to test against
env:
  matrix:
   - DJANGO_VERSION=2.2

services:
  - postgresql

install:
  - pip install -r requirements.txt
   # Install whatever version of Django that's listed above
  - pip install -q Django==$DJANGO_VERSION

script:
  - python -m black . -l 80 --check
  - python manage.py makemigrations
  - python manage.py migrate
  - python -m coverage coverage run --source='.' manage.py test --parallel
  - python -m coverage report --skip-covered --omit="setup.py,interface/wsgi.py,django_queryset_constraint/tests/*,django_queryset_constraint/migrations/*"
  - python -m isort -c
