# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_constraint_triggers.models
import django_constraint_triggers.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disallow1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disallow12In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disallow12Multi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disallow12Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disallow13GT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        django_constraint_triggers.operations.AddConstraintTrigger(
            model_name='disallow13gt',
            trigger_name='GTE1',
            query=django_constraint_triggers.models.M(app_label=None, model='Disallow13GT', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age__gte': 1}, 'type': '__call__'}]),
        ),
        django_constraint_triggers.operations.AddConstraintTrigger(
            model_name='disallow12range',
            trigger_name='GTE1LTE2',
            query=django_constraint_triggers.models.M(app_label=None, model='Disallow12Range', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age__gte': 1}, 'type': '__call__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age__lte': 2}, 'type': '__call__'}]),
        ),
        django_constraint_triggers.operations.AddConstraintTrigger(
            model_name='disallow12multi',
            trigger_name='1',
            query=django_constraint_triggers.models.M(app_label=None, model='Disallow12Multi', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age': 1}, 'type': '__call__'}]),
        ),
        django_constraint_triggers.operations.AddConstraintTrigger(
            model_name='disallow12multi',
            trigger_name='2',
            query=django_constraint_triggers.models.M(app_label=None, model='Disallow12Multi', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age': 2}, 'type': '__call__'}]),
        ),
        django_constraint_triggers.operations.AddConstraintTrigger(
            model_name='disallow12in',
            trigger_name='IN12',
            query=django_constraint_triggers.models.M(app_label=None, model='Disallow12In', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age__in': [1, 2]}, 'type': '__call__'}]),
        ),
        django_constraint_triggers.operations.AddConstraintTrigger(
            model_name='disallow1',
            trigger_name='1',
            query=django_constraint_triggers.models.M(app_label=None, model=None, operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age': 1}, 'type': '__call__'}]),
        ),
    ]
