# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django_constraint_triggers.models
import django_constraint_triggers.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneAndTwoNotAllowedTwoConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OneNotAllowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        django_constraint_triggers.operations.AddConstraintTrigger(
            model_name='onenotallowed',
            trigger_name='disallow_one',
            query=django_constraint_triggers.models.M(app_label=None, model='OneNotAllowed', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age': 1}, 'type': '__call__'}]),
        ),
        django_constraint_triggers.operations.AddConstraintTrigger(
            model_name='oneandtwonotallowedtwoconstraints',
            trigger_name='disallow_one',
            query=django_constraint_triggers.models.M(app_label=None, model='OneAndTwoNotAllowedTwoConstraints', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age': 1}, 'type': '__call__'}]),
        ),
        django_constraint_triggers.operations.AddConstraintTrigger(
            model_name='oneandtwonotallowedtwoconstraints',
            trigger_name='disallow_two',
            query=django_constraint_triggers.models.M(app_label=None, model='OneAndTwoNotAllowedTwoConstraints', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age': 2}, 'type': '__call__'}]),
        ),
    ]
