# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_constraint_triggers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
