# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 14:32
from __future__ import unicode_literals

from django.db import migrations
import django_constraint_triggers.models
import django_constraint_triggers.operations


class Migration(migrations.Migration):

    dependencies = [
        ('django_constraint_triggers', '0002_allowall'),
    ]

    operations = [
        django_constraint_triggers.operations.RemoveConstraintTrigger(
            model_name='disallow12range',
            trigger_name='GTE1LTE2',
            query=django_constraint_triggers.models.M(app_label=None, model='Disallow12Range', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age__gte': 1}, 'type': '__call__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age__lte': 2}, 'type': '__call__'}]),
        ),
        django_constraint_triggers.operations.RemoveConstraintTrigger(
            model_name='disallow12in',
            trigger_name='IN12',
            query=django_constraint_triggers.models.M(app_label=None, model='Disallow12In', operations=[{'name': b'objects', 'type': '__getattribute__'}, {'name': b'filter', 'type': '__getattribute__'}, {'args': (), 'kwargs': {b'age__in': [1, 2]}, 'type': '__call__'}]),
        ),
    ]
